# warden.toml
[rules]
max_file_tokens = 2000
max_cyclomatic_complexity = 8
max_nesting_depth = 3
max_function_args = 5
max_function_words = 5
ignore_naming_on = ["tests", "spec"]
ignore_tokens_on = ["lock", ".md"]

[commands]
check = [
    "cargo clippy --all-targets -- -D warnings -D clippy::pedantic",
    "cargo test"
]
fix = "cargo fmt"
